version: '3.9'
volumes:
  pg_data: { }
networks:
  frontend: { }
  backend: { }
services:
  aplikasi:
    image: demo-aplikasi-rsup:v1
    networks:
      - backend
      - frontend
    depends_on:
      - database
  frontend:
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    depends_on:
      - aplikasi
  database:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend