version: '3.9'
volumes:
  pg_data: { }
services:
  aplikasi:
    image: demo-aplikasi-rsup:v1
    ports:
      - "8080:8080"
  frontend:
    image: nginx:mainline
    ports:
      - "9080:9090"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  database:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data