management:
  tracing:
    sampling:
      probability: 1.0
  wavefront:
    application:
      service-name: ${spring.application.name}
  health:
    diskspace:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "resume,pause,restart,refresh,metrics,threaddump,heapdump,info,health,health-path"
spring:
  application:
    name: rsup-wahidin-demo
