apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rsup
  labels:
    app: demo-rsup
    tier: backend
    version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rsup
      tier: backend
      version: stable
  template:
    metadata:
      name: demo-rsup
      labels:
        app: demo-rsup
        tier: backend
        version: stable
    spec:
      containers:
        - name: demo-rsup
          image: 10.12.10.49:8087/training/rsup-wahidin:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
